FROM php:8.1-fpm-alpine
LABEL maintainer="jess@mintopia.net"

ARG S6_OVERLAY_VERSION=3.1.0.1

RUN apk update \
    && apk --no-cache add \
        ${PHPIZE_DEPS} \
        freetype-dev\
        libpng-dev \
        libjpeg-turbo-dev \
        nginx \
    # Remove (some of the) default nginx config
    && rm -f /etc/nginx.conf /etc/nginx/conf.d/default.conf \
    && rm -rf /etc/nginx/sites-* \
    # Ensure nginx logs, even if the config has errors, are written to stderr
    && ln -s /dev/stderr /var/lib/nginx/logs/error.log \
    && chmod -R 777 /var/log/nginx /var/lib/nginx \
    && pecl install -o -f redis \
    && pecl install -f xdebug \
    && docker-php-ext-enable xdebug \
    && rm -rf /tmp/pear \
    && docker-php-ext-install \
        bcmath \
        pdo_mysql \
    && docker-php-ext-configure gd \
        --with-freetype \
        --with-jpeg \
    && docker-php-ext-install gd \
    && docker-php-ext-enable redis \
    && apk del --no-cache ${PHPIZE_DEPS} \
    && rm -vrf /tmp/pear /var/cache/apk/* \
    && mkdir -p /var/www /tmp \
    && chown -R 1000:1000 /var/www /tmp

COPY files /

# Install s6 overlay for service management

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp/
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp/
RUN \
    tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz

WORKDIR /var/www/
USER 1000
ENV HOME /tmp

EXPOSE 8000

ENTRYPOINT ["/init"]
