#!/bin/sh
set -e

# Clear and re-cache artisan routes
php /var/www/artisan route:clear -n
php /var/www/artisan route:cache -n

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"
