FROM ghcr.io/mintopia/php-docker-php-fpm:latest
LABEL maintainer="jess@mintopia.net"

USER root

RUN apk update \
    && apk --no-cache add \
        ${PHPIZE_DEPS} linux-headers\
    && pecl install -f xdebug \
    && docker-php-ext-enable xdebug \
    && rm -rf /tmp/pear \
    && apk del --no-cache ${PHPIZE_DEPS} \
    && rm -vrf /tmp/pear /var/cache/apk/* \

USER 1000
